In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("mediamill.csv")

In [12]:
df.head()

,Att1,Att2,Att3,Att4,Att5,Att6,Att7,Att8,Att9,Att10,...,Class94,Class95,Class96,Class97,Class98,Class99,Class100,Class101,.labelcount,.SCUMBLE
0,0.380877,0.494079,0.540009,0.422926,0.158318,0.326975,0.390861,0.527121,0.254052,0.223731,...,0,0,0,0,0,0,0,0,4,0.273702
1,0.508613,0.505837,0.437155,0.490723,0.262201,0.459610,0.393838,0.524006,0.370391,0.329424,...,0,0,0,0,0,0,0,0,4,0.703351
2,0.449571,0.460490,0.453469,0.410779,0.231759,0.402147,0.349590,0.536456,0.318117,0.301615,...,0,0,0,0,0,0,0,0,3,0.206882
3,0.416800,0.548996,0.520850,0.465410,0.181603,0.357255,0.389347,0.530189,0.290942,0.244521,...,0,0,0,0,0,0,0,0,3,0.395520
4,0.501986,0.480820,0.435543,0.432002,0.250599,0.408353,0.357816,0.499186,0.353172,0.327622,...,0,0,0,0,0,0,0,0,3,0.206882

In [13]:
df.iloc[:, 0: 120]

,Att1,Att2,Att3,Att4,Att5,Att6,Att7,Att8,Att9,Att10,...,Att111,Att112,Att113,Att114,Att115,Att116,Att117,Att118,Att119,Att120
0,0.380877,0.494079,0.540009,0.422926,0.158318,0.326975,0.390861,0.527121,0.254052,0.223731,...,0.593651,0.551529,0.574392,0.511032,0.463997,0.202034,0.492341,0.317983,0.547807,0.393778
1,0.508613,0.505837,0.437155,0.490723,0.262201,0.459610,0.393838,0.524006,0.370391,0.329424,...,0.616601,0.556555,0.553718,0.552479,0.511739,0.218366,0.547476,0.348174,0.584991,0.422205
2,0.449571,0.460490,0.453469,0.410779,0.231759,0.402147,0.349590,0.536456,0.318117,0.301615,...,0.627463,0.539564,0.638607,0.496368,0.480986,0.199592,0.535078,0.323834,0.571487,0.397564
3,0.416800,0.548996,0.520850,0.465410,0.181603,0.357255,0.389347,0.530189,0.290942,0.244521,...,0.604669,0.557365,0.571348,0.565105,0.497706,0.252656,0.546756,0.346506,0.589601,0.430145
4,0.501986,0.480820,0.435543,0.432002,0.250599,0.408353,0.357816,0.499186,0.353172,0.327622,...,0.607607,0.543372,0.566417,0.526322,0.484486,0.186909,0.564721,0.325957,0.578370,0.398771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43902,0.426864,0.528629,0.532957,0.401551,0.187178,0.328457,0.363949,0.487699,0.306376,0.266459,...,0.610354,0.544168,0.553511,0.580699,0.559847,0.348502,0.587482,0.488400,0.624835,0.527380
43903,0.344094,0.537319,0.516101,0.430633,0.147998,0.310974,0.373041,0.493417,0.249852,0.191468,...,0.582064,0.527097,0.581796,0.555630,0.515736,0.271329,0.520354,0.410659,0.564902,0.453231
43904,0.329709,0.453422,0.523771,0.314048,0.133553,0.249196,0.296952,0.440839,0.222037,0.196553,...,0.574960,0.522756,0.594364,0.567564,0.524449,0.232201,0.554800,0.408484,0.570778,0.453345
43905,0.470031,0.489588,0.488227,0.356816,0.228900,0.370288,0.327771,0.464365,0.347709,0.319948,...,0.585344,0.494285,0.566579,0.555662,0.544435,0.244654,0.575187,0.422255,0.585876,0.464987
43906,0.350638,0.548779,0.554297,0.404750,0.134141,0.284098,0.361868,0.465428,0.241016,0.199843,...,0.561277,0.542575,0.601334,0.563842,0.556132,0.289604,0.564673,0.448091,0.589267,0.497985

In [14]:
df.iloc[:, 120: 221]

,Class1,Class2,Class3,Class4,Class5,Class6,Class7,Class8,Class9,Class10,...,Class92,Class93,Class94,Class95,Class96,Class97,Class98,Class99,Class100,Class101
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43902,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
43903,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
43904,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
43905,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43906,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [20]:
import torch
A = torch.tensor(df.iloc[:, 0: 120].to_numpy())
B = torch.tensor(df.iloc[:, 120: 221].to_numpy())

In [21]:
# save to tensor that C++ can load directly

from torch import nn
class TensorContainer(nn.Module):
    def __init__(self, tensor_dict):
        super().__init__()
        for key,value in tensor_dict.items():
            setattr(self, key, value)

tensor_dict = {
    "A": A,
    "B": B
}
tensors = TensorContainer(tensor_dict)
tensors = torch.jit.script(tensors)
tensors.save('mediamill.pth')